// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptjycinvxpzifplxpmwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0anljaW52eHB6aWZwbHhwbXdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDU4NDMsImV4cCI6MjA2NDM4MTg0M30.ECvcHh5ydQLFVMLVNdFJAblBLntnR-8c9BR013tCeLk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});